version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  backend-spring:
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "6868:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
  .m2:
