version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  backend-spring:
    container_name: backend-spring
    image: aymenkhairoune/springimage:latest
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8082:8082"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
