version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  backend-spring:
    container_name: backend-spring
    image: aymenkhairoune/springimage:${BUILD_NUMBER}
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8082:8082"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network
    depends_on:
      - backend-spring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - my-network
    depends_on:
      - prometheus

networks:
  my-network:
    driver: bridge

volumes:
  db:
  grafana:
