version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  spring-app:
    container_name: spring-app
    image: naderayed/devops:${BUILD_NUMBER}
    depends_on:
      - mysqldb
    ports:
      - "8086:8086"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mysql-data:
