version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  backend-spring:
    build: .
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "6868:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  .m2:
